---
title: "index"
author: "Selina Sun"
date: "2/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(results = "hide")
```

## 670 Lab Assignment 
Source: [The World Bank: World Development Indicators](https://databank.worldbank.org/source/world-development-indicators#)

```{r}
library(readr)
library(tidyverse)
library(ggplot2)
library(janitor)
library(maps)
```

```{r}
data <-read_csv("2ec6e98c-8ba1-49c1-a2b0-6fa5c6d718e5_Data.csv") %>%
  clean_names()%>%
  rename(c("2011" = "x2011_yr2011", "2012" = "x2012_yr2012", "2013" = "x2013_yr2013","2014" = "x2014_yr2014", "2015" = "x2015_yr2015")) %>%
  select(-"series_code") %>%
  filter(!is.na(country_code)) %>%
  pivot_longer(
    cols = c(4:8),
    names_to = "year",
    values_to = "values"
  ) %>%
  pivot_wider(
    names_from = "series_name", 
    values_from = "values"
  ) %>%
  clean_names() %>%
  mutate_at(
    c(4:75), as.numeric
  )

gdp_energy<-data %>%
  filter(year == 2014 &
 !is.na(gdp_per_unit_of_energy_use_constant_2017_ppp_per_kg_of_oil_equivalent))%>%
  select(country_name, gdp_per_unit_of_energy_use_constant_2017_ppp_per_kg_of_oil_equivalent)%>%
  rename(region=country_name,GDP_per_energy = gdp_per_unit_of_energy_use_constant_2017_ppp_per_kg_of_oil_equivalent)%>%
  mutate(region=ifelse(region == "United States", "USA", region),
         region=ifelse(region == "Korea, Dem. People's Rep.", "South Korea", region),
         region=ifelse(region=="Russian Federation", "Russia", region),
         region=ifelse(region=="United Kingdom", "UK", region)
  )
world<-map_data("world")
gdp_energy2017<-left_join(gdp_energy, world, by="region")

vis3<-ggplot(gdp_energy2017, aes(x=long, y=lat, group=group))+
    geom_polygon(aes(fill = GDP_per_energy), color = "white")+
    scale_fill_viridis_c(option = "viridis")
vis3
```
```{r}
intensity<-data%>%
  as.data.frame(data)%>%
  filter(year==2014 & 
    !is.na(energy_intensity_level_of_primary_energy_mj_2011_ppp_gdp)& 
    !is.na(co2_intensity_kg_per_kg_of_oil_equivalent_energy_use)&
  country_code %in% c("ARG","AUS", "BRA", "CAN","CHN", "FRA", "DEU", "IND", "IDN", 
                      "ITA", "JPN", "KOR", "MEX","RUS", "SAU", "ZAF","TUR","GBR", "USA", "EUU"))%>%
  select(country_code, energy_intensity_level_of_primary_energy_mj_2011_ppp_gdp, 
         co2_intensity_kg_per_kg_of_oil_equivalent_energy_use)%>%
  rename(energy_intensity = energy_intensity_level_of_primary_energy_mj_2011_ppp_gdp,
         co2_intensity= co2_intensity_kg_per_kg_of_oil_equivalent_energy_use)%>%
  pivot_longer(!country_code, names_to = "intensity_level", 
               values_to = "values")%>%

 ggplot(intensity, mapping=aes(country_code, values, fill=intensity_level
         ) )+
 geom_bar(stat="identity", position="dodge", alpha=.6, width = .8)+
 coord_flip()+
 scale_fill_discrete(name = "Intensity Level", 
                     labels = c("CO2 Intensity Kg Per Kg of Oil Equivalent Energy Use", 
                                "Energy Intensity Level of Primary Energy(MJ/Constant 2011 PPP GDP)"
 ))+
  
  labs(
  x = "Latest Year Available (2014)",
  y = "Intensity Level",
  title = "Energy and CO2 Intensity Across G20 Countries",
  subtitle = "By Energy Intensity And By C02 Intensity",
  caption = "The World Bank: [World Development Indicators](https://databank.worldbank.org/source/world-development-indicators#)")+
  theme_minimal() +
  theme(
    axis.title = element_text(size = 9),
    axis.text = element_text(size = 8),
    plot.title = element_text(hjust = 0.5, size = 10),
    plot.subtitle = element_text(hjust = 0.5, size = 9),
    plot.caption = element_text(hjust = 0, size =7, face = "italic"),
    legend.title = element_text(size = 8),
    legend.text = element_text(size = 8),
    legend.position = "bottom"
  ) +
  guides(color = FALSE, fill = guide_legend(nrow = 2))
 
intensity
```
